#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in5,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in6,    centerLine,     sensorLineFollower)
#pragma config(Sensor, in7,    leftLine,       sensorLineFollower)
#pragma config(Sensor, dgtl2,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
		while (SensorValue[rightEncoder] > -1000) {
			motor[armMotor] = -90;
			motor[rightMotor] = 127;
			motor[leftMotor] = 127;
		}
		stopMotor(rightMotor);
		stopMotor(leftMotor);
		stopMotor(armMotor);
		wait(1);
		motor[clawMotor] = 70;
		wait(1);
		stopMotor(clawMotor);
		motor[rightMotor] = -30;
		motor[leftMotor] = -30;
		motor[clawMotor] = -127;
		wait(1.5);
		stopMotor(rightMotor);
		stopMotor(leftMotor);
		stopMotor(clawMotor);
}
