#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in5,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl2,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task auton() {
	boolean allianceColor = false; // false is red, true is blue
	int blue = 500;
	int red = 700;
	boolean deposit = false; // false is keep going, true is stop
	if (allianceColor) {
		while (SensorValue[lineFollower] == blue) {
				motor[rightMotor] = 127;
				motor[leftMotor] = 127;
		}
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		motor[clawMotor] = 50;
		wait(2);
		motor[clawMotor] = 0;
	}
	else {
		while (SensorValue[lineFollower] == blue) {
				motor[rightMotor] = 127;
				motor[leftMotor] = 127;
		}
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		motor[clawMotor] = 50;
		wait(2);
		motor[clawMotor] = 0;
	}


}
